/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.141.0Release
// Tag = production/release/21.141.0-0-g2aa27e1
/////////////////////////////////////////////////////////////////////////////////////////////

const sanitizeValues = (values) => {
    if (onlyNullValues(values)) {
        return null
    }

    return values.length === 1 ? values[0] : values
}

const onlyNullValues = (values) => values.reduce((state, value) => (value != null ? false : state), true)

const onlyInvalidValues = (rawFieldValue, invalidValue) => {
    if (Array.isArray(rawFieldValue)) {
        return rawFieldValue.reduce((state, value) => (value != invalidValue ? false : state), true)
    }

    return rawFieldValue === invalidValue
}

export default {
    sanitizeValues,
    onlyNullValues,
    onlyInvalidValues
}
